- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 72000 #20 hrs # Corvax-RoleTime
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - Detective
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: DetectiveGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltHolster
    underpants: ClothingUnderpanties_alt #backmen
    undershirt: ClothingUnderundershirt #backmen
    socks: ClothingUnderSocks_norm  #backmen
  storage:
    back:
    - Flash
    - ForensicPad
    - ForensicScanner
    belt:
    - SpeedLoaderMagnum

