- type: startingGear
  id: CluwneGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCluwne
    back: ClothingBackpackCluwne
    shoes: ClothingShoesCluwne
    mask: ClothingMaskCluwne
    pda: CluwnePDA
    gloves: ClothingHandsGlovesCluwne
    pocket1: CluwneHorn
    id: Wallet # space cats add_id_revork

- type: startingGear
  id: HoloClownGear
  equipment:
    pocket1: BikeHorn

