#Misc outfit startingGear definitions.

#Skeleton Biker - Just a skeleton now
- type: startingGear
  id: SkeletonBiker
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpack
    head: ClothingHeadBandSkull
    eyes: ClothingEyesGlassesSunglasses
    outerClothing: ClothingOuterCoatGentle
    gloves: ClothingHandsGlovesFingerless
    shoes: ClothingShoesBootsJack
    pda: PassengerPDA
    ears: ClothingHeadsetGrey
    id: Wallet # space cats add_id_revork

#Deathsquad Outfit
- type: startingGear
  id: DeathSquadGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad
    back: ClothingBackpackDeathSquad
    mask: ClothingMaskGasDeathSquad
    eyes: ClothingEyesHudSecurity
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitDeathsquad
    shoes: ClothingShoesBootsMagAdv
    pda: DeathsquadPDA
    pocket1: EnergySword
    pocket2: EnergyShield
    belt: ClothingBeltMilitaryWebbingMedFilled
    id: Wallet # space cats add_id_revork
  storage:
    back:
    - WeaponPulsePistol
    - WeaponRevolverMateba
    - SpeedLoaderMagnumAP
    - SpeedLoaderMagnumAP
    - BoxFlashbang
    - ToolDebug # spanish army knife
    - WelderExperimental
    - Hypospray
    - DeathAcidifierImplanter # crew will try to steal their amazing hardsuits
    - FreedomImplanter
  inhand:
  - WeaponPulseRifle

# Syndicate Operative Outfit - Civilian
- type: startingGear
  id: SyndicateOperativeGearCivilian
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndieFormal
    back: ClothingBackpackDuffelSyndicate
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesColorBlack
    pda: SyndiPDA
    ears: ClothingHeadsetAltSyndicate
    id: Wallet # space cats add_id_revork

# Syndicate Footsoldier Gear - No Headset
- type: startingGear
  id: SyndicateFootsoldierGearRuin
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    head: ClothingHeadHelmetSwatSyndicate
    mask: ClothingMaskGas
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpack
    shoes: ClothingShoesBootsCombat
    pda: SyndiPDA
    id: Wallet # space cats add_id_revork
  storage:
    back:
    - BoxSurvival

# Syndicate Footsoldier Gear
- type: startingGear
  id: SyndicateFootsoldierGear
  parent: SyndicateFootsoldierGearRuin
  equipment:
    ears: ClothingHeadsetAltSyndicate

# Nanotrasen Paramilitary Unit Gear
- type: startingGear
  id: NanotrasenParamilitaryGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetSwat
    mask: ClothingMaskGasSwat
    outerClothing: ClothingOuterArmorBasicSlim
    ears: ClothingHeadsetSecurity
    gloves: ClothingHandsGlovesCombat
    id: Wallet # space cats add_id_revork
  storage:
    back:
    - BoxSurvivalSecurity
    - Flash
    - MagazinePistol

#CBURN Unit Gear - Full Kit
- type: startingGear
  id: CBURNGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackDuffelCBURN
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitCBURN
    shoes: ClothingShoesBootsCombatFilled
    pda: CBURNPDA
    pocket1: RadioHandheld
    pocket2: WeaponLaserGun
    belt: ClothingBeltBandolier
    id: Wallet # space cats add_id_revork
  storage:
    back:
    - WeaponShotgunDoubleBarreled
    - BoxShotgunIncendiary
    - GrenadeFlashBang
    - PillAmbuzolPlus
    - PillAmbuzol

- type: startingGear
  id: BoxingKangarooGear
  equipment:
    gloves: ClothingHandsGlovesBoxingBlue
    id: Wallet # space cats add_id_revork

- type: startingGear
  id: MobMonkeyGear
  equipment:
    head: ClothingHeadHatTophat
    ears: ClothingHeadsetService
    jumpsuit: ClothingUniformJumpsuitJacketMonkey
    pda: PunPunIDCard
    id: Wallet # space cats add_id_revork

# DeathMatch Gear

- type: startingGear
  id: DeathMatchGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    shoes: ClothingShoesBootsJack
    ears: ClothingHeadsetGrey
    gloves: ClothingHandsGlovesFingerless
    id: Wallet # space cats add_id_revork
  inhand:
    - WeaponMeleeToolboxRobust

#Brigmedic

- type: startingGear
  id: BrigmedicGearOld
  equipment:
    jumpsuit: ClothingUniformJumpsuitBrigmedic
    outerClothing: ClothingOuterCoatAMG
    back: ClothingBackpackBrigmedic
    shoes: ClothingShoesColorRed
    gloves: ClothingHandsGlovesNitrile
    eyes: ClothingEyesHudMedical
    head: ClothingHeadHatBeretBrigmedic
    pda: BrigmedicPDA
    ears: ClothingHeadsetBrigmedic
    mask: ClothingMaskBreathMedicalSecurity
    belt: ClothingBeltMedicalFilled
    id: Wallet # space cats add_id_revork

# Aghost
- type: startingGear
  id: MobAghostGear
  equipment:
    back: ClothingBackpackSatchelHolding
    pda: AdminPDA
    id: Wallet # space cats add_id_revork
  storage:
    back:
    - GasAnalyzer
    - trayScanner
    - AccessConfiguratorUniversal

#Gladiator with spear
- type: startingGear
  id: GladiatorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGladiator
    back: SpearBone
    head: ClothingHeadHatGladiator
    shoes: ClothingShoesCult
    id: Wallet # space cats add_id_revork

#Ash Walker
- type: startingGear
  id: AshWalker
  equipment:
    jumpsuit: ClothingUniformJumpsuitGladiator
    outerClothing: ClothingOuterArmorBone
    back: SpearBone
    head: ClothingHeadHelmetBone
    shoes: ClothingShoesCult
    id: Wallet # space cats add_id_revork

#Banana Clown
- type: startingGear
  id: BananaClown
  equipment:
    pda: ClownPDA
    back: ClothingBackpackClown
    shoes: ClothingShoesClownBanana
    jumpsuit: ClothingUniformJumpsuitClownBanana
    mask: ClothingMaskClownBanana
    pocket1: BikeHorn
    pocket2: ClownRecorder
    id: Wallet # space cats add_id_revork

# Passenger but without the ID, bag, or headset
- type: startingGear
  id: LimitedPassengerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    shoes: ClothingShoesColorBlack
    id: Wallet # space cats add_id_revork

#Clown Troupe
- type: startingGear
  id: ClownTroupe
  equipment:
    jumpsuit: ClothingUniformJumpsuitClown
    shoes: ClothingShoesClown
    pda: ClownPDA
    back: ClothingBackpackClown
    ears: ClothingHeadsetService
    mask: ClothingMaskClown
    pocket1: BikeHorn
    pocket2: ClownRecorder
    id: Wallet # space cats add_id_revork

#Lost Cargo Tech
- type: startingGear
  id: LostCargoTechGearSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitCargo
    shoes: ClothingShoesColorBlack
    head: ClothingHeadHatCargosoft
    pda: CargoPDA
    back: ClothingBackpackCargo
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
    id: Wallet # space cats add_id_revork

- type: startingGear
  id: LostCargoTechGearCoat
  equipment:
    jumpsuit: ClothingUniformJumpsuitCargo
    shoes: ClothingShoesBootsWinterCargo
    head: ClothingHeadHatCargosoft
    pda: CargoPDA
    back: ClothingBackpackDuffelCargo
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
    outerClothing: ClothingOuterWinterCargo
    id: Wallet # space cats add_id_revork

#Traveling Chef
- type: startingGear
  id: TravelingChef
  equipment:
    jumpsuit: ClothingUniformJumpsuitChef
    shoes: ClothingShoesColorWhite
    pda: ChefPDA
    back: ClothingBackpackSatchel
    ears: ClothingHeadsetService
    belt: ClothingBeltChef
    id: Wallet # space cats add_id_revork

#CMO Disaster Victim
- type: startingGear
  id: DisasterVictimCMO
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMO
    shoes: ClothingShoesColorBrown
    head: ClothingHeadMirror
    neck: ClothingCloakCmo
    pda: CMOPDA
    back: ClothingBackpackMedical
    ears: ClothingHeadsetCMO
    belt: ClothingBeltMedical
    outerClothing: ClothingOuterCoatLabCmo
    id: Wallet # space cats add_id_revork

- type: startingGear
  id: DisasterVictimCMOAlt
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMOTurtle
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatBeretCmo
    neck: ClothingNeckMantleCMO
    pda: CMOPDA
    back: ClothingBackpackSatchelMedical
    ears: ClothingHeadsetCMO
    belt: ClothingBeltMedical
    outerClothing: ClothingOuterCoatLabCmo
    id: Wallet # space cats add_id_revork

#Captain Disaster Victim
- type: startingGear
  id: DisasterVictimCaptain
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    head: ClothingHeadHatCaptain
    neck: ClothingNeckCloakCap
    pda: CaptainPDA
    back: ClothingBackpackCaptain
    ears: ClothingHeadsetAltCommand
    outerClothing: ClothingOuterArmorCaptainCarapace
    id: Wallet # space cats add_id_revork

- type: startingGear
  id: DisasterVictimCaptainAlt
  equipment:
    jumpsuit: ClothingUniformJumpsuitCapFormal
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    head: ClothingHeadHatCapcap
    neck: ClothingNeckMantleCap
    pda: CaptainPDA
    back: ClothingBackpackSatchelCaptain
    ears: ClothingHeadsetAltCommand
    outerClothing: ClothingOuterArmorCaptainCarapace
    id: Wallet # space cats add_id_revork

#RD Disaster Victim
- type: startingGear
  id: DisasterVictimRD
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatBeretRND
    neck: ClothingNeckCloakRd
    pda: RnDPDA
    back: ClothingBackpackScience
    ears: ClothingHeadsetRD
    outerClothing: ClothingOuterCoatRD
    id: Wallet # space cats add_id_revork

- type: startingGear
  id: DisasterVictimRDAlt
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatBeretRND
    neck: ClothingNeckMantleRD
    pda: RnDPDA
    back: ClothingBackpackSatchelScience
    ears: ClothingHeadsetRD
    outerClothing: ClothingOuterCoatRD
    id: Wallet # space cats add_id_revork
