#Wizard outfit startingGear definitions.
- type: startingGear
  id: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorDarkBlue
    head: ClothingHeadHatWizard
    outerClothing: ClothingOuterWizard
    shoes: ClothingShoesWizard
    id: PassengerPDA
    ears: ClothingHeadsetService
    underpants: ClothingUnderpanties_alt #backmen
    undershirt: ClothingUnderundershirt #backmen
    socks: ClothingUnderSocks_norm  #backmen
  storage:
    back:
    - BoxSurvival

- type: startingGear
  id: WizardRedGear
  parent: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorRed
    head: ClothingHeadHatRedwizard
    outerClothing: ClothingOuterWizardRed
    underpants: ClothingUnderpanties_alt #backmen
    undershirt: ClothingUnderundershirt #backmen
    socks: ClothingUnderSocks_norm  #backmen

- type: startingGear
  id: WizardVioletGear
  parent: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorPurple
    head: ClothingHeadHatVioletwizard
    outerClothing: ClothingOuterWizardViolet
    underpants: ClothingUnderpanties_alt #backmen
    undershirt: ClothingUnderundershirt #backmen
    socks: ClothingUnderSocks_norm  #backmen

- type: startingGear
  id: WizardHardsuitGear
  parent: WizardVioletGear
  equipment:
    outerClothing: ClothingOuterHardsuitWizard
    underpants: ClothingUnderpanties_alt #backmen
    undershirt: ClothingUnderundershirt #backmen
    socks: ClothingUnderSocks_norm  #backmen
