#Wizard outfit startingGear definitions.
- type: startingGear
  id: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorDarkBlue
    head: ClothingHeadHatWizard
    outerClothing: ClothingOuterWizard
    shoes: ClothingShoesWizard
    pda: PassengerPDA
    ears: ClothingHeadsetService
    id: Wallet # space cats add_id_revork
  storage:
    back:
    - BoxSurvival

- type: startingGear
  id: WizardRedGear
  parent: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorRed
    head: ClothingHeadHatRedwizard
    outerClothing: ClothingOuterWizardRed
    id: Wallet # space cats add_id_revork

- type: startingGear
  id: WizardVioletGear
  parent: WizardBlueGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorPurple
    head: ClothingHeadHatVioletwizard
    outerClothing: ClothingOuterWizardViolet
    id: Wallet # space cats add_id_revork

- type: startingGear
  id: WizardHardsuitGear
  parent: WizardVioletGear
  equipment:
    outerClothing: ClothingOuterHardsuitWizard
    id: Wallet # space cats add_id_revork
