- type: job
  id: Boxer
  name: job-name-boxer
  description: job-description-boxer
  playTimeTracker: JobBoxer
  startingGear: BoxerGear
  icon: "JobIconBoxer"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  #end-backmen: currency

- type: startingGear
  id: BoxerGear
  equipment:
    pda: BoxerPDA
    ears: ClothingHeadsetService
    shoes: ClothingShoesColorRed
    belt: ClothingBeltChampion
    id: Wallet # space cats add_id_revork
  #storage:
    #back:
    #- Stuff
