- type: job
  id: Passenger
  name: job-name-passenger
  description: job-description-passenger
  playTimeTracker: JobPassenger
  startingGear: PassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
#  access: # Corvax-MRP
#  - Maintenance
  #start-backmen: currency
  minBankBalance: 50
  maxBankBalance: 400
  #end-backmen: currency

- type: startingGear
  id: PassengerGear
  equipment:
    pda: PassengerPDA
    ears: ClothingHeadsetGrey
    id: Wallet # space cats add_id_revork
  #storage:
    #back:
    #- Stuff
