- type: startingGear
  id: CannedClownGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitClown
    back: ClothingBackpackClown
    shoes: ClothingShoesClown
    mask: ClothingMaskClown
    pocket1: BikeHorn
    id: ClownIDCard
    neck: FoodTinClownSoupcanTrash
    underpants: ClothingUnderpanties_alt #backmen
    undershirt: ClothingUnderundershirt #backmen
    socks: ClothingUnderSocks_norm  #backmen
  #satchel: ClothingBackpackSatchelClown
  #duffelbag: ClothingBackpackDuffelClown
