name: Notify Discord on PR Merge to Master

on:
  pull_request:
    types: [closed]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
    - name: Check if PR is merged into master and send notification to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        PR_TITLE=$(jq -r '.pull_request.title' $GITHUB_EVENT_PATH)
        PR_BODY=$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH)
        PR_USER=$(jq -r '.pull_request.user.login' $GITHUB_EVENT_PATH)
        PR_MERGED=$(jq -r '.pull_request.merged' $GITHUB_EVENT_PATH)
        PR_MERGED_AT=$(jq -r '.pull_request.merged_at' $GITHUB_EVENT_PATH)
        PR_BASE_REF=$(jq -r '.pull_request.base.ref' $GITHUB_EVENT_PATH)

        if [ "$PR_MERGED" != "true" ] || [ "$PR_BASE_REF" != "master" ]; then
          echo "PR was not merged into master, skipping notification."
          exit 0
        fi

        if [ "$PR_MERGED_AT" != "null" ]; then
          MERGED_TIME=$(date -d "$PR_MERGED_AT" --utc +'%Y-%m-%dT%H:%M:%SZ')
        else
          MERGED_TIME="Not available"
        fi

        if [ "$PR_BODY" != "" ]; then
          CHANGES=$(echo "$PR_BODY" | grep -E '^(add|remove|tweak|fix):' || echo "No change details found")
        else
          CHANGES="No change details found"
        fi

        PAYLOAD=$(jq -n \
          --arg title "$PR_TITLE" \
          --arg description "$PR_BODY" \
          --arg changes "$CHANGES" \
          --arg user "$PR_USER" \
          --arg merged_time "$MERGED_TIME" \
          '{
            "embeds": [{
              "title": $title,
              "description": "\($description)\n\n**Changes**:\n$changes\n\n**Author**: $user\n**Merged At**: $merged_time",
              "color": 65280  # Зеленый, так как PR принят
            }]
          }')

        echo "$PAYLOAD" | curl -H "Content-Type: application/json" -d @- $DISCORD_WEBHOOK_URL
