name: Notify Discord

on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
    - name: Send notification to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        PR_TITLE=$(jq -r '.pull_request.title' $GITHUB_EVENT_PATH)
        PR_URL=$(jq -r '.pull_request.html_url' $GITHUB_EVENT_PATH)
        PR_USER=$(jq -r '.pull_request.user.login' $GITHUB_EVENT_PATH)
        PR_BODY=$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH)
        PR_STATE=$(jq -r '.action' $GITHUB_EVENT_PATH)

        if [ "$PR_STATE" == "opened" ]; then
          EMBED_COLOR=65280 
        elif [ "$PR_STATE" == "closed" ]; then
          EMBED_COLOR=16711680
        elif [ "$PR_STATE" == "reopened" ]; then
          EMBED_COLOR=16776960
        else
          EMBED_COLOR=16777215 
        fi

        PAYLOAD=$(jq -n \
          --arg title "$PR_TITLE" \
          --arg url "$PR_URL" \
          --arg user "$PR_USER" \
          --arg body "$PR_BODY" \
          --argjson color "$EMBED_COLOR" \
          '{
            "embeds": [{
              "title": $title,
              "url": $url,
              "author": {
                "name": $user
              },
              "description": $body,
              "color": $color
            }]
          }')

        echo "$PAYLOAD" | curl -H "Content-Type: application/json" -d @- $DISCORD_WEBHOOK_URL
