name: PR Notify

on:
  pull_request:
    types: [closed]

jobs:
  discordNotification:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up jq
      run: sudo apt-get install -y jq

    - name: Send Discord Notification
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        PR_TITLE=$(jq -r .pull_request.title $GITHUB_EVENT_PATH)
        PR_USER=$(jq -r .pull_request.user.login $GITHUB_EVENT_PATH)

        JSON_PAYLOAD=$(cat <<EOF
        {
          "username": "GitHub Actions",
          "embeds": [{
            "title": "Принят PR: ${PR_TITLE}",
            "fields": [
              {
                "name": "Автор",
                "value": "${PR_USER}",
                "inline": true
              }
            ]
          }]
        }
        EOF
        )

        echo "JSON Payload: $JSON_PAYLOAD"

        curl -H "Content-Type: application/json" -d "$JSON_PAYLOAD" $DISCORD_WEBHOOK_URL




