name: PR Notify

on:
  pull_request:
    types: [closed]

jobs:
  discordNotification:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Send Discord Notification
      uses: actions/github-script@v6
      with:
        script: |
          const { data } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });

          const prTitle = data.title;
          const prUser = data.user.login;
          const prBody = data.body;
          const prMergedAt = new Date(data.merged_at).toISOString();
          const prMergedAtDate = new Date(data.merged_at).toLocaleString();

          const tweakRegex = /^-\s*tweak:\s*(.*)$/mg;
          const addRegex = /^-\s*add:\s*(.*)$/mg;
          const fixRegex = /^-\s*fix:\s*(.*)$/mg;
          const removeRegex = /^-\s*remove:\s*(.*)$/mg;

          let tweaks = '';
          let adds = '';
          let fixes = '';
          let removes = '';

          let match;
          while ((match = tweakRegex.exec(prBody)) !== null) {
            tweaks += `\n🛠️ ${match[1]}`;
          }
          while ((match = addRegex.exec(prBody)) !== null) {
            adds += `\n➕ ${match[1]}`;
          }
          while ((match = fixRegex.exec(prBody)) !== null) {
            fixes += `\n🔧 ${match[1]}`;
          }
          while ((match = removeRegex.exec(prBody)) !== null) {
            removes += `\n❌ ${match[1]}`;
          }

          const changes = `${tweaks}${adds}${fixes}${removes}`;

          const webhookUrl = process.env.DISCORD_WEBHOOK_URL;

          const axios = require('axios');
          await axios.post(webhookUrl, {
            username: 'Space-Cats | [Development]',
            avatar_url: 'https://media.discordapp.net/attachments/1250152873250132073/1263212035366326363/space-cats_logo_space_1.png?ex=669b63a2&is=669a1222&hm=a99c299e22f2a48b152b83b59069004ad94dc261dcc44de03564285729f8e586&=&format=webp&quality=lossless&width=115&height=115',
            embeds: [{
              title: `Принят PR: ${prTitle}`,
              description: `**Описание:**\n${prBody}\n\n**Изменения:**${changes}`,
              color: 3066993,
              timestamp: prMergedAt,
              footer: {
                text: `Merged at ${prMergedAtDate}`
              },
              fields: [
                {
                  name: 'Статус',
                  value: 'Merged',
                  inline: true
                },
                {
                  name: 'Автор',
                  value: prUser,
                  inline: true
                }
              ]
            }]
          });
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
